spring:
  profiles:
    active: dev
  application:
    name: basic-x
  data:
    redis:
      host: 10.10.110.241
      port: 6379
      password:
      timeout: 10000
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.110.241:3306/wms_init?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#logging:
#  config: classpath:log4j2-${spring.profiles.active}.xml